server:
  port: 8090
  servlet:
    context-path: /solrServer
spring:
  application:
    name: solrServer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.203.128:3306/emall3?characterEncoding=utf-8&useSSL=false
  data:
    solr:
      host: http://192.168.203.128:8088/solr

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.huang.demo1.entity